### ISSUE TITLE
Please Can I Join This Organisation? 🥺🙏"

### ISSUE THREAD

**Issue by MohitGupta121** [App-Choreography/Get-An-Invite#14]
## Name: Mohit Gupta

I want to Join this Community as I'm start contributing to Open Source projects from last 6 months and want to gain more experience. Collaborate with amazing community.
I'm waiting for your response going forward with amazing community.

**Comment by CodingSpecies** [comment]
#15 
this has been addressed. Thank you for opening this issue!
