### ISSUE TITLE
Please Can I Join This Organisation? 🥺🙏

### ISSUE THREAD

**Issue by MohitGupta121** [App-Choreography/Get-An-Invite#15]
## Info About the Pull Request You Made: 

> You can put the number of your pull request, but putting `#` with the number your pull request is at.

**Comment by AvidCoder101** [comment]
@MohitGupta121 please follow the PR steps on the README so that you can make a contribution, and then you can be added as a member

**Comment by CodingSpecies** [comment]
@MohitGupta121 I will send an invite for you. Please take a look around our org if you wish to contribute! Thank you for opening this issue!

**Comment by CodingSpecies** [comment]
###### [Our Website 🌐](https://app-choreography.github.io/) | [Repositories 📚](https://github.com/orgs/App-Choreography/repositories) | [LinkFree Profile 🔗](http://linkfree.eddiehub.org/App-Choreography)

You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

### When you join our org, you will be automatically be part of our community team, where you will get updates, and news about our org!

### We are so happy you have joined! Welcome to App Choreography! 🥳

**Comment by MohitGupta121** [comment]
By mistake I press decline button of invitation can you please send it again.

**Comment by CodingSpecies** [comment]
@MohitGupta121 i have resent it. Thank you
