### ISSUE TITLE
Please Can I Join This Organisation? 🥺🙏"

### ISSUE THREAD

**Issue by Estevamsl** [App-Choreography/Get-An-Invite#19]
## Name: 
- Estevamsl

## Info About the Pull Request You Made: 
- Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

**Comment by CodingSpecies** [comment]
###### [Our Website 🌐](https://app-choreography.github.io/) | [Repositories 📚](https://github.com/orgs/App-Choreography/repositories) | [LinkFree Profile 🔗](http://linkfree.eddiehub.org/App-Choreography)

@Estevamsl , You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)

### When you join our org, you will be automatically be part of our community team, where you will get updates, and news about our org!

### We are so happy you have joined! Welcome to App Choreography! 🥳

**Comment by CodingSpecies** [comment]
>  Because I want to stay on top of everything that goes on in this organization and of course, as a good dev, you have to know about the challenges of this incredible world of programming

Welcome @Estevamsl! Here is a few things you can do in this org:

- [App-Choreo's Community team chat](https://github.com/orgs/App-Choreography/teams/community) = Here you see the latest updates, can share your ideas and collaborate!
- [GitHub Profile League](https://github.com/App-Choreography/GitHubProfileLeague) = submit your GitHub profile readme, to be in the chance of winning! **2 entries left to fill!**
- [Hacktoberfest Practice](https://github.com/App-Choreography/HacktoberfestPracticePage) = practice your Hacktoberfest.
- [Best App Tutorials](https://github.com/App-Choreography/Best-App-Tutorials-3) = see the latest app tutorials you can either add or take a look at.
- [Fix our Readme](https://github.com/App-Choreography/Fix-Our-Readme) = Here you can polish your code debugging/review and GitHub skills.
- [Best GitHub Open Source](https://github.com/App-Choreography/Best-GitHub-OpenSource) = See the best GitHub opensource repos!

For any help or support, feel free to ask.
Thank you.
