### ISSUE TITLE
Please Can I Join This Organisation? 🥺🙏

### ISSUE THREAD

**Issue by m0lese** [App-Choreography/Get-An-Invite#2]
## Info About the Pull Request You Made: 
Added myself to the [Successful members, which contributed to this repo](https://github.com/App-Choreography/Get-An-Invite#-successful-members-which-contributed-to-this-repo---).

> You can put the number of your pull request, but putting `#` with the number your pull request is at.

#1

**Comment by CodingSpecies** [comment]
You have received an email to join, or press this link - https://github.com/App-Choreography - , and you'll see a banner, for you to join the organisation! 🎉 

You can also show that you are part of this org, by making yourself public. This will show our profile org on your profile:
## Follow This:
1. After you join the organisation, search your name in the list of people. 🔍 
2.  Follow this below: ⬇️ 
![image](https://user-images.githubusercontent.com/70807500/130362669-7eb8ac9f-41e3-489e-b88b-1fe180e18129.png)
