### ISSUE TITLE
404 m0lese link

### ISSUE THREAD

**Issue by BaseMax** [App-Choreography/Get-An-Invite#36]
[https://github.com/m0lese](https://github.com/m0lese)

**Comment by BaseMax** [comment]
source: https://github.com/App-Choreography/Get-An-Invite/blob/main/README.md#-successful-members-which-contributed-to-this-repo---

**Comment by CodingSpecies** [comment]
Thank you for pointing this out @BaseMax .
As this user is no longer on GitHub, I will remove it. Thank you.

**Comment by CodingSpecies** [comment]
https://github.com/App-Choreography/Get-An-Invite/commit/b82569bfbb5297ffd0a10353a9d99e9427a3dbc9
Completed. Thank you for your help @BaseMax .
