### ISSUE TITLE
Please Can I Join This Organisation? 🙏

### ISSUE THREAD

**Issue by doBestMan** [App-Choreography/Get-An-Invite#86]
## Name: 

Hi, Nice to meet you.
My name is DoBestMan

## Pull request with your contribution

I tried to push my contribute to open a Pull reguest but it's denied to me. Please let me know how I can fix this.

![image](https://user-images.githubusercontent.com/110788393/226727564-988795c1-756d-4fd9-8d8a-d201ff364f0a.png)

**Comment by CodingSpecies** [comment]
> 

Hi @doBestMan . Welcome to App Choreography.
Have you forked this repo first before adding your changes?
Thanks.
